#端口号 上下文
server:
  port: 8080
  servlet:
    context-path: /crm
# 数据源
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/citiccrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  #freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/


  #启动热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

#配置mybatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.software.crm.bean
  configuration:
    map-underscore-to-camel-case: true
#分页
pagehelper:
  helper-dialect: mysql

#dao 日志
logging:
  level:
    com:
      software:
        crm:
          mapper: debug

